%
% libs.pl
% marelle-deps
%
pacman_pkg('lib32-alsa-plugins').
pacman_pkg('lib32-fakeroot').
pacman_pkg('lib32-libpulse').
aur_pkg('lib32-libxaw').
pacman_pkg('lib32-ncurses').
pacman_pkg('lib32-sdl').
pacman_pkg('lib32-sqlite').
debian_pkg('libasound2-dev').
debian_pkg('libassuan-dev').
debian_pkg('libavdevice54').
debian_pkg('libboost-all-dev').
debian_pkg('libcap-dev').
debian_pkg('libevdev-dev').
pacman_pkg('libevdev').
aur_pkg('libevhtp').
debian_pkg('libfam0').
debian_pkg('libgcrypt11-dev').
debian_pkg('libglib2.0-doc').
debian_pkg('libgmime-2.6-dev').
debian_pkg('libgmp3-dev').
debian_pkg('libgtk-3-dev').
debian_pkg('libgtkglext1-dev').
debian_pkg('libimlib2-dev').
debian_pkg('libjson-glib-dev').
debian_pkg('libksba-dev').
debian_pkg('libldap2-dev').
debian_pkg('liblwp-protocol-socks-perl').
debian_pkg('libncurses5-dev').
debian_pkg('libnotify-bin').
debian_pkg('libnotify-dev').
debian_pkg('libnpth0-dev').
debian_pkg('libperl-dev').
aur_pkg('libpng15').
debian_pkg('libpurple-dev').
debian_pkg('libpython-dev').
debian_pkg('libpython3-dev').
debian_pkg('libsasl2-dev').
debian_pkg('libsdl1.2-dev').
debian_pkg('libsigsegv-dev').
debian_pkg('libspeexdsp-dev').
debian_pkg('libssl-dev').
debian_pkg('libxapian-dev').
debian_pkg('libxcb-icccm4-dev').
debian_pkg('libxcb-keysyms1-dev').
debian_pkg('libxcb-randr0-dev').
debian_pkg('libxcb-util0-dev').
debian_pkg('libxml2-dev').
